name=CzechArduino
version=1.2.0
author=Javor
maintainer=Javor <javor@javoris.eu>
sentence=Arduino knihovna pro české uživatele.
paragraph=Arduino knihovna pro české uživatele.
category=Uncategorized
url=https://github.com/Javorxdd/CzechArduino
architectures=*