name=CzechArduino
version=1.0.0
author=Javor
maintainer=Javor
sentence=Knihovna CzechArduino.
paragraph=Popis funkce knihovny CzechArduino.
category=Uncategorized
url=https://github.com/Javorxdd/CzechArduino
architectures=*